apiVersion: v2
name: integrador-chart
description: A Helm chart for deploying a Python app with PostgreSQL
version: 0.1.1
dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
